# replace clock_bridge
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

# replace odom_tf_bridge 
- ros_topic_name: "tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: false

# replace IMU 
- ros_topic_name: "imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false

# replace 3d_lidar 
# - ros_topic_name: "/front_laser_sensor/points"
#   gz_topic_name: "/front_laser_sensor/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "gz.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS
#   lazy: false

# replace navsat 
# - ros_topic_name: "/robot/gps/fix"
#   gz_topic_name: "/robot/gps/fix"
#   ros_type_name: "sensor_msgs/msg/NavSatFix"
#   gz_type_name: "gz.msgs.NavSat"
#   direction: GZ_TO_ROS
#   lazy: false
