controller_manager:
  ros__parameters:
    update_rate: 20 # Hz

    rover_base_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/**/rover_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["wheel_left_front_joint", "wheel_left_back_joint"]
    right_wheel_names: ["wheel_right_front_joint", "wheel_right_back_joint"]
    wheel_separation: 1.90
    wheel_radius: 0.30
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    # Base frame_id
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0

/**/scara_controller:
  ros__parameters:
    joints:
    - arm_1_link_joint
    - arm_2_link_joint
    - arm_3_link_joint
    - gripper_link_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    
/**/gripper_controller:
  ros__parameters:
    joints:
    - gripper_left_link_joint
    - gripper_right_link_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    allow_nonzero_velocity_at_trajectory_end: true
